# PyTorch Tensors & NumPy Array Methods

In [1]:
import torch
import numpy as np
print(torch.__version__)
print(np.__version__)

2.11.0+cpu
2.3.5


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## 1. Creating A Tensor

### a. Using empty

In [3]:
a = torch.empty(2, 3)
a

tensor([[6.2382e+26, 1.3747e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
b = np.empty([2, 3])
b

array([[1.33360345e+241, 6.37838908e+073, 1.00259045e+074],
       [1.33360346e+241, 6.37999255e-310, 4.31912683e-239]])

In [5]:
type(a), type(b)

(torch.Tensor, numpy.ndarray)

### b. Using zeros

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

### c. Using ones

In [8]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### d. Using rand

In [10]:
torch.rand(2, 3)

tensor([[0.5298, 0.9190, 0.7943],
        [0.1981, 0.9062, 0.8965]])

In [11]:
np.random.rand(2, 3)

array([[0.60898087, 0.37612479, 0.15886584],
       [0.332997  , 0.28307322, 0.67583041]])

#### d1. Seeding torch rand

In [12]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

#### d2. Seeding numpy rand

In [13]:
np.random.seed(100)
np.random.rand(2, 3)

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912]])

### e. Custom tensors

In [14]:
torch.tensor([[1, 2, 3],
             [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
np.array([[1, 2, 3],
         [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Creating A Tensor: Other Methods

### a. arange

In [16]:
torch.arange(0, 10, 2) # start, end, step

tensor([0, 2, 4, 6, 8])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### b. linspace

In [18]:
torch.linspace(0, 10, 10) # start, end, evenly spaced vals

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [19]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### c. Indentity matrix

In [20]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### d. Full

In [22]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [23]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## 3. Tensor Shapes & Copy

In [24]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [25]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y.shape

(2, 3)

### a. Empty

In [26]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
np.empty_like(y)

array([[4603069776131998572, 4598686276953825018, 4601319048971945986],
       [4605784286494731230, 4572090492933402368, 4593424399016102400]])

### b. Zeros

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
np.zeros_like(y)

array([[0, 0, 0],
       [0, 0, 0]])

### c. Ones

In [31]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
np.ones_like(y)

array([[1, 1, 1],
       [1, 1, 1]])

### d. Rand

In [33]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [34]:
np.random.rand(*y.shape)

array([[0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212]])

## 4. Tensor Data Types

In [35]:
x.dtype

torch.int64

In [36]:
y.dtype

dtype('int64')

### a. Assigning data type

In [37]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [38]:
np.array([1.0, 2.0, 3.0], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [39]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [40]:
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

### b. Casting data type

In [41]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [42]:
y.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### c. List of all data types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## 5. Mathematical Operations

### a. Scalar operation

In [43]:
s = torch.tensor([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
t = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [44]:
a = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = np.array([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

#### addition

In [45]:
t + 2

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [46]:
a + 2

array([[3., 4., 5.],
       [6., 7., 8.]])

#### subtraction

In [47]:
t - 2

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])

In [48]:
a - 2

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

#### multiplication

In [49]:
t * 2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [50]:
a * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

#### division

In [51]:
t / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [52]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [53]:
t // 3

tensor([[0., 0., 1.],
        [1., 1., 2.]])

In [54]:
a // 3

array([[0., 0., 1.],
       [1., 1., 2.]])

#### mod

In [55]:
t % 2

tensor([[1., 0., 1.],
        [0., 1., 0.]])

In [56]:
a % 2

array([[1., 0., 1.],
       [0., 1., 0.]])

#### power

In [57]:
t ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [58]:
a ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### b. Element wise operation

#### addition

In [59]:
s + t

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.]])

In [60]:
a + b

array([[ 3.,  5.,  7.],
       [ 9., 11., 13.]])

#### subtraction

In [61]:
s - t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [62]:
b - a

array([[1., 1., 1.],
       [1., 1., 1.]])

#### multiplication

In [63]:
s * t

tensor([[ 2.,  6., 12.],
        [20., 30., 42.]])

In [64]:
a * b

array([[ 2.,  6., 12.],
       [20., 30., 42.]])

#### division

In [65]:
s / t

tensor([[2.0000, 1.5000, 1.3333],
        [1.2500, 1.2000, 1.1667]])

In [66]:
b / a

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667]])

In [67]:
s // t

tensor([[2., 1., 1.],
        [1., 1., 1.]])

In [68]:
b // a

array([[2., 1., 1.],
       [1., 1., 1.]])

#### power

In [69]:
s ** t

tensor([[2.0000e+00, 9.0000e+00, 6.4000e+01],
        [6.2500e+02, 7.7760e+03, 1.1765e+05]])

In [70]:
b ** a

array([[2.00000e+00, 9.00000e+00, 6.40000e+01],
       [6.25000e+02, 7.77600e+03, 1.17649e+05]])

#### mod

In [71]:
s % t

tensor([[0., 1., 1.],
        [1., 1., 1.]])

In [72]:
b % a

array([[0., 1., 1.],
       [1., 1., 1.]])

#### abs

In [73]:
u = torch.full((2, 3), -1)
u

tensor([[-1, -1, -1],
        [-1, -1, -1]])

In [74]:
torch.abs(u)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [75]:
c = np.full((2, 3), -1)
c

array([[-1, -1, -1],
       [-1, -1, -1]])

In [76]:
np.abs(c)

array([[1, 1, 1],
       [1, 1, 1]])

#### negative

In [77]:
torch.neg(t)

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [78]:
np.negative(a)

array([[-1., -2., -3.],
       [-4., -5., -6.]])

In [79]:
-a

array([[-1., -2., -3.],
       [-4., -5., -6.]])

#### round

In [80]:
v = torch.rand(2, 3)
v

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [81]:
d = np.random.rand(2, 3)
d

array([[0.18532822, 0.10837689, 0.21969749],
       [0.97862378, 0.81168315, 0.17194101]])

In [82]:
torch.round(v)

tensor([[1., 1., 0.],
        [1., 1., 1.]])

In [83]:
np.round(d)

array([[0., 0., 0.],
       [1., 1., 0.]])

#### ceil

In [84]:
torch.ceil(v)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [85]:
np.ceil(d)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### floor

In [86]:
torch.floor(v)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [87]:
np.floor(d)

array([[0., 0., 0.],
       [0., 0., 0.]])

#### clamp

In [88]:
torch.clamp(v, min=0.5, max=1)

tensor([[0.7118, 0.7876, 0.5000],
        [0.9014, 0.9969, 0.7565]])

In [89]:
np.clip(d, 0.5, 1)

array([[0.5       , 0.5       , 0.5       ],
       [0.97862378, 0.81168315, 0.5       ]])

## 6. Reduction Operation

### a. Summation

In [90]:
s

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [91]:
# Sum of all values

torch.sum(s)

tensor(27.)

In [92]:
b

array([[2., 3., 4.],
       [5., 6., 7.]])

In [93]:
np.sum(b)

np.float64(27.0)

In [94]:
# Sum along columns
torch.sum(s, dim=0)

tensor([ 7.,  9., 11.])

In [95]:
s.sum(axis=0)

tensor([ 7.,  9., 11.])

In [96]:
np.sum(b, axis=0)

array([ 7.,  9., 11.])

In [97]:
b.sum(axis=0)

array([ 7.,  9., 11.])

In [98]:
# Sum along rows
torch.sum(s, dim=1)

tensor([ 9., 18.])

In [99]:
np.sum(b, axis=1)

array([ 9., 18.])

### b. Mean

In [100]:
# Mean of all values
torch.mean(s)

tensor(4.5000)

In [101]:
np.mean(b)

np.float64(4.5)

In [102]:
# Mean along columns
torch.mean(s, dim=0)

tensor([3.5000, 4.5000, 5.5000])

In [103]:
np.mean(b, axis=0)

array([3.5, 4.5, 5.5])

In [104]:
# Mean along rows
torch.mean(s, axis=1)

tensor([3., 6.])

In [105]:
np.mean(b, axis=1)

array([3., 6.])

### c. Min & Max

In [106]:
# Min/Max of all values
torch.min(s), torch.max(s)

(tensor(2.), tensor(7.))

In [107]:
np.min(b), np.max(b)

(np.float64(2.0), np.float64(7.0))

In [108]:
# Min/Max along columns
torch.min(s, dim=0)

torch.return_types.min(
values=tensor([2., 3., 4.]),
indices=tensor([0, 0, 0]))

In [109]:
torch.max(s, dim=0)

torch.return_types.max(
values=tensor([5., 6., 7.]),
indices=tensor([1, 1, 1]))

In [110]:
np.min(b, axis=0)

array([2., 3., 4.])

In [111]:
np.max(b, axis=0)

array([5., 6., 7.])

In [112]:
# Min/Max along rows
torch.min(s, dim=1), torch.max(s, dim=1)

(torch.return_types.min(
 values=tensor([2., 5.]),
 indices=tensor([0, 0])),
 torch.return_types.max(
 values=tensor([4., 7.]),
 indices=tensor([2, 2])))

In [113]:
np.min(b, axis=1), np.max(b, axis=1)

(array([2., 5.]), array([4., 7.]))

### d. argmax & argmin

In [114]:
torch.argmin(s)

tensor(0)

In [115]:
torch.argmax(s)

tensor(5)

In [116]:
np.argmin(b)

np.int64(0)

In [117]:
np.argmax(b)

np.int64(5)

### e. Product

In [118]:
torch.prod(s)

tensor(5040.)

In [119]:
np.prod(b)

np.float64(5040.0)

### f. Standard deviation

In [120]:
torch.std(s)

tensor(1.8708)

In [121]:
np.std(b)

np.float64(1.707825127659933)

### g. Variance

In [122]:
torch.var(s)

tensor(3.5000)

In [123]:
np.var(b)

np.float64(2.9166666666666665)

## 7. Matrix Operations

In [124]:
s = torch.randint(size=(2, 3), low=0, high=10)
t = torch.randint(size=(3, 2), low=0, high=10)

In [125]:
s

tensor([[4, 3, 8],
        [7, 4, 6]])

In [126]:
t

tensor([[0, 1],
        [9, 9],
        [8, 0]])

In [127]:
a = np.random.randint(size=(2, 3), low=0, high=10)
b = np.random.randint(size=(3, 2), low=0, high=10)

In [128]:
a

array([[5, 3, 4],
       [4, 3, 7]], dtype=int32)

In [129]:
b

array([[1, 1],
       [7, 7],
       [0, 2]], dtype=int32)

### a. Matrix Multiplication

In [130]:
torch.matmul(s, t)

tensor([[91, 31],
        [84, 43]])

In [131]:
np.matmul(a, b)

array([[26, 34],
       [25, 39]], dtype=int32)

### b. Dot Product

In [132]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

torch.dot(vector1, vector2)

tensor(11)

In [133]:
vector3 = np.array([1, 2])
vector4 = np.array([3, 4])

np.dot(vector3, vector4)

np.int64(11)

### c. Transpose

In [134]:
torch.transpose(s, 0, 1)

tensor([[4, 7],
        [3, 4],
        [8, 6]])

In [135]:
np.transpose(a)

array([[5, 4],
       [3, 3],
       [4, 7]], dtype=int32)

### d. Determinant

In [136]:
u = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
u

tensor([[7., 0., 0.],
        [9., 5., 7.],
        [3., 9., 4.]])

In [137]:
torch.det(u)

tensor(-301.)

In [138]:
c = np.random.uniform(size=(3, 3), low=0, high=10)
c

array([[2.52426353, 7.95662508, 0.15254971],
       [5.98843377, 6.03804539, 1.05147685],
       [3.81943445, 0.36476057, 8.90411563]])

In [139]:
np.linalg.det(c)

np.float64(-260.74653962517556)

### e. Inverse

In [140]:
torch.inverse(u)

tensor([[ 1.4286e-01,  0.0000e+00, -6.6227e-09],
        [ 4.9834e-02, -9.3023e-02,  1.6279e-01],
        [-2.1927e-01,  2.0930e-01, -1.1628e-01]])

In [141]:
np.linalg.inv(c)

array([[-0.20471956,  0.27149379, -0.02855303],
       [ 0.18909421, -0.08396537,  0.00667572],
       [ 0.08006846, -0.11301801,  0.12428201]])

## 8. Comparison Operations

In [142]:
it = torch.randint(size=(2, 3), low=0, high=10)
jt = torch.randint(size=(2, 3), low=0, high=10)

print(it)
print(jt)

tensor([[0, 5, 7],
        [5, 9, 9]])
tensor([[7, 5, 9],
        [8, 9, 7]])


In [143]:
inp = np.random.randint(size=(2, 3), low=0, high=10)
jnp = np.random.randint(size=(2, 3), low=0, high=10)

print(inp)
print(jnp)

[[2 0 8]
 [2 5 1]]
[[8 1 5]
 [4 2 8]]


In [144]:
it > jt

tensor([[False, False, False],
        [False, False,  True]])

In [145]:
inp > jnp

array([[False, False,  True],
       [False,  True, False]])

All comparison operators are supported in similar to the example above.

## 9. Special Functions

### a. log

In [146]:
torch.log(s)

tensor([[1.3863, 1.0986, 2.0794],
        [1.9459, 1.3863, 1.7918]])

In [147]:
np.log(b)

C:\Users\HP\AppData\Local\Temp\ipykernel_3836\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[0.        , 0.        ],
       [1.94591015, 1.94591015],
       [      -inf, 0.69314718]])

### b. exp

In [148]:
torch.exp(s)

tensor([[  54.5981,   20.0855, 2980.9580],
        [1096.6332,   54.5981,  403.4288]])

In [149]:
np.exp(a)

array([[ 148.4131591 ,   20.08553692,   54.59815003],
       [  54.59815003,   20.08553692, 1096.63315843]])

### c. sqrt

In [150]:
torch.sqrt(s)

tensor([[2.0000, 1.7321, 2.8284],
        [2.6458, 2.0000, 2.4495]])

In [151]:
np.sqrt(a)

array([[2.23606798, 1.73205081, 2.        ],
       [2.        , 1.73205081, 2.64575131]])

### d. Sigmoid

In [152]:
torch.sigmoid(s)

tensor([[0.9820, 0.9526, 0.9997],
        [0.9991, 0.9820, 0.9975]])

In [153]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-2, 0, 2])
print(sigmoid(x))

[0.11920292 0.5        0.88079708]


### e. Softmax

In [154]:
torch.softmax(u, dim=0)

tensor([[1.1894e-01, 1.2118e-04, 8.6788e-04],
        [8.7888e-01, 1.7984e-02, 9.5175e-01],
        [2.1785e-03, 9.8189e-01, 4.7385e-02]])

In [155]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x = np.array([1, 2, 3])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]


In [156]:
torch.softmax(torch.tensor([1.0, 2.0, 3.0]), dim=-1)

tensor([0.0900, 0.2447, 0.6652])

### f. ReLu

In [162]:
torch.relu(u)

tensor([[7., 0., 0.],
        [9., 5., 7.],
        [3., 9., 4.]])

In [163]:
def relu(x):
    return np.maximum(0, x)

x = np.array([-2, -1, 0, 3])
print(relu(x))

[0 0 0 3]


## 10. Inplace Operations

In [164]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])
tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])


In [165]:
m.add_(n)

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [166]:
m

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [167]:
o = np.random.randint(size=(2, 3), low=0, high=10)
p = np.random.randint(size=(2, 3), low=0, high=10)

In [168]:
np.add(o, p, out=o) # or o += p

array([[ 6,  9,  7],
       [15,  6, 15]], dtype=int32)

In [169]:
o

array([[ 6,  9,  7],
       [15,  6, 15]], dtype=int32)

In [170]:
u = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
u

tensor([[4., 3., 8.],
        [8., 3., 3.],
        [5., 0., 6.]])

In [171]:
u.sigmoid_()

tensor([[0.9820, 0.9526, 0.9997],
        [0.9997, 0.9526, 0.9526],
        [0.9933, 0.5000, 0.9975]])

In [172]:
u

tensor([[0.9820, 0.9526, 0.9997],
        [0.9997, 0.9526, 0.9526],
        [0.9933, 0.5000, 0.9975]])

Note: Suffixing an underscore to the method makes it an inplace operation.

## 11. Copying a Tensor

In [173]:
a = torch.rand(2,3)
a

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

### Referenced copy

In [174]:
b = a

In [175]:
b

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [176]:
a[0][0] = 0
a

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [177]:
b

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [178]:
id(a), id(b)

(2732499195520, 2732499195520)

### Cloned copy

In [179]:
b = a.clone()

In [180]:
a[0][0] = 1
a

tensor([[1.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [181]:
b

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [182]:
id(a), id(b)

(2732499195520, 2732498139600)

## 12. Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.6146, 0.7502, 0.8164],
        [0.2579, 0.6280, 0.4347]], device='cuda:0')

In [7]:
# moving an existing tensor to GPU
t = torch.rand(2, 3)
t

tensor([[0.9788, 0.9670, 0.6672],
        [0.1342, 0.0434, 0.4591]])

In [9]:
gt = t.to(device)
gt

tensor([[0.9788, 0.9670, 0.6672],
        [0.1342, 0.0434, 0.4591]], device='cuda:0')

In [10]:
gt + 5

tensor([[5.9788, 5.9670, 5.6672],
        [5.1342, 5.0434, 5.4591]], device='cuda:0')

In [11]:
import time

size = 10000 # Large matrix size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 7.481740 seconds
Time on GPU: 0.728763 seconds

Speedup (CPU time / GPU time): 10.266350962081098


## 13. Reshaping Tensors

In [12]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
b = np.ones([4, 4])
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### a. reshape

In [14]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [15]:
b.reshape(2, 2, 2, 2)

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

### b. flatten

In [16]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### c. permute

In [20]:
a = torch.ones(2, 3, 4)
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [23]:
b = np.ones([2, 3, 4])
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
a.permute(2, 0, 1)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [26]:
b.transpose(2, 0, 1)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### d. unsqueeze

In [27]:
a = torch.rand(226, 226, 3)

In [28]:
a.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [31]:
b = np.random.rand(226, 226, 3)

In [34]:
np.expand_dims(b, axis=0).shape

(1, 226, 226, 3)

### e. squeeze

In [35]:
a = torch.rand(1, 20)
a.shape

torch.Size([1, 20])

In [36]:
a.squeeze(0).shape

torch.Size([20])

In [38]:
b = np.expand_dims(b, axis=0)
b.shape

(1, 226, 226, 3)

In [40]:
b.squeeze().shape

(226, 226, 3)

## 14. NumPy and PyTorch

In [41]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [44]:
b = a.numpy()
b

array([1, 2, 3])

In [45]:
torch.from_numpy(b)

tensor([1, 2, 3])