# PyTorch Tensors & NumPy Array Methods

In [1]:
import torch
import numpy as np
print(torch.__version__)
print(np.__version__)

2.8.0+cu126
2.0.2


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## 1. Creating A Tensor

### a. Using empty

In [7]:
a = torch.empty(2, 3)
a

tensor([[-7.7464e-30,  4.4090e-41, -7.7464e-30],
        [ 4.4090e-41,  1.4013e-45,  0.0000e+00]])

In [8]:
b = np.empty([2, 3])
b

array([[1.73020193e-315, 0.00000000e+000, 2.15922555e+185],
       [7.36507368e+228, 9.29433782e+242, 0.00000000e+000]])

In [9]:
type(a), type(b)

(torch.Tensor, numpy.ndarray)

### b. Using zeros

In [10]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

### c. Using ones

In [13]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### d. Using rand

In [15]:
torch.rand(2, 3)

tensor([[0.0248, 0.3521, 0.6963],
        [0.2994, 0.5018, 0.3004]])

In [18]:
np.random.rand(2, 3)

array([[0.74667063, 0.71851904, 0.87112119],
       [0.40670708, 0.67131159, 0.77116465]])

#### d1. Seeding torch rand

In [19]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

#### d2. Seeding numpy rand

In [23]:
np.random.seed(100)
np.random.rand(2, 3)

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912]])

### e. Custom tensors

In [25]:
torch.tensor([[1, 2, 3],
             [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
np.array([[1, 2, 3],
         [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Creating A Tensor: Other Methods

### a. arange

In [32]:
torch.arange(0, 10, 2) # start, end, step

tensor([0, 2, 4, 6, 8])

In [29]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### b. linspace

In [33]:
torch.linspace(0, 10, 10) # start, end, evenly spaced vals

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [34]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### c. Indentity matrix

In [35]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### d. Full

In [37]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [38]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## 3. Tensor Shapes & Copy

In [41]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [42]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y.shape

(2, 3)

### a. Empty

In [43]:
torch.empty_like(x)

tensor([[3616445622929465956, 6066966817701637430, 3833753161491427632],
        [6499316792844300590, 7309453675965983778, 8315168162784306286]])

In [44]:
np.empty_like(y)

array([[4603069776131998572, 4598686276953825018, 4601319048971945986],
       [4605784286494731230, 4572090492933402368, 4593424399016102400]])

### b. Zeros

In [45]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [46]:
np.zeros_like(y)

array([[0, 0, 0],
       [0, 0, 0]])

### c. Ones

In [47]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [48]:
np.ones_like(y)

array([[1, 1, 1],
       [1, 1, 1]])

### d. Rand

In [63]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [67]:
np.random.rand(*y.shape)

array([[0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212]])

## 4. Tensor Data Types

In [50]:
x.dtype

torch.int64

In [51]:
y.dtype

dtype('int64')

### a. Assigning data type

In [52]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [54]:
np.array([1.0, 2.0, 3.0], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [55]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [56]:
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

### b. Casting data type

In [57]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [60]:
y.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### c. List of all data types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## 5. Mathematical Operations

### a. Scalar operation

In [2]:
s = torch.tensor([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
t = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
a = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = np.array([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

#### addition

In [5]:
t + 2

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [6]:
a + 2

array([[3., 4., 5.],
       [6., 7., 8.]])

#### subtraction

In [7]:
t - 2

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])

In [8]:
a - 2

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

#### multiplication

In [9]:
t * 2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [10]:
a * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

#### division

In [11]:
t / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [12]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [13]:
t // 3

tensor([[0., 0., 1.],
        [1., 1., 2.]])

In [14]:
a // 3

array([[0., 0., 1.],
       [1., 1., 2.]])

#### mod

In [15]:
t % 2

tensor([[1., 0., 1.],
        [0., 1., 0.]])

In [16]:
a % 2

array([[1., 0., 1.],
       [0., 1., 0.]])

#### power

In [17]:
t ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [18]:
a ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### b. Element wise operation

#### addition

In [21]:
s + t

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.]])

In [22]:
a + b

array([[ 3.,  5.,  7.],
       [ 9., 11., 13.]])

#### subtraction

In [23]:
s - t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
b - a

array([[1., 1., 1.],
       [1., 1., 1.]])

#### multiplication

In [26]:
s * t

tensor([[ 2.,  6., 12.],
        [20., 30., 42.]])

In [27]:
a * b

array([[ 2.,  6., 12.],
       [20., 30., 42.]])

#### division

In [28]:
s / t

tensor([[2.0000, 1.5000, 1.3333],
        [1.2500, 1.2000, 1.1667]])

In [29]:
b / a

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667]])

In [34]:
s // t

tensor([[2., 1., 1.],
        [1., 1., 1.]])

In [35]:
b // a

array([[2., 1., 1.],
       [1., 1., 1.]])

#### power

In [30]:
s ** t

tensor([[2.0000e+00, 9.0000e+00, 6.4000e+01],
        [6.2500e+02, 7.7760e+03, 1.1765e+05]])

In [31]:
b ** a

array([[2.00000e+00, 9.00000e+00, 6.40000e+01],
       [6.25000e+02, 7.77600e+03, 1.17649e+05]])

#### mod

In [32]:
s % t

tensor([[0., 1., 1.],
        [1., 1., 1.]])

In [33]:
b % a

array([[0., 1., 1.],
       [1., 1., 1.]])

#### abs

In [36]:
u = torch.full((2, 3), -1)
u

tensor([[-1, -1, -1],
        [-1, -1, -1]])

In [37]:
torch.abs(u)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [38]:
c = np.full((2, 3), -1)
c

array([[-1, -1, -1],
       [-1, -1, -1]])

In [39]:
np.abs(c)

array([[1, 1, 1],
       [1, 1, 1]])

#### negative

In [42]:
torch.neg(t)

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

In [45]:
np.negative(a)

array([[-1., -2., -3.],
       [-4., -5., -6.]])

In [46]:
-a

array([[-1., -2., -3.],
       [-4., -5., -6.]])

#### round

In [48]:
v = torch.rand(2, 3)
v

tensor([[0.6316, 0.0769, 0.2563],
        [0.3010, 0.5425, 0.3959]])

In [50]:
d = np.random.rand(2, 3)
d

array([[0.31785512, 0.31047036, 0.68494649],
       [0.17267031, 0.36427884, 0.37217965]])

In [52]:
torch.round(v)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [53]:
np.round(d)

array([[0., 0., 1.],
       [0., 0., 0.]])

#### ceil

In [54]:
torch.ceil(v)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [55]:
np.ceil(d)

array([[1., 1., 1.],
       [1., 1., 1.]])

#### floor

In [56]:
torch.floor(v)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [57]:
np.floor(d)

array([[0., 0., 0.],
       [0., 0., 0.]])

#### clamp

In [59]:
torch.clamp(v, min=0.5, max=1)

tensor([[0.6316, 0.5000, 0.5000],
        [0.5000, 0.5425, 0.5000]])

In [62]:
np.clip(d, 0.5, 1)

array([[0.5       , 0.5       , 0.68494649],
       [0.5       , 0.5       , 0.5       ]])

## 6. Reduction Operation

### a. Summation

In [74]:
s

tensor(27.)

In [68]:
# Sum of all values

torch.sum(s)

tensor(27.)

In [66]:
b

array([[2., 3., 4.],
       [5., 6., 7.]])

In [67]:
np.sum(b)

np.float64(27.0)

In [69]:
# Sum along columns
torch.sum(s, dim=0)

tensor([ 7.,  9., 11.])

In [75]:
s.sum(axis=0)

tensor([ 7.,  9., 11.])

In [71]:
np.sum(b, axis=0)

array([ 7.,  9., 11.])

In [73]:
b.sum(axis=0)

array([ 7.,  9., 11.])

In [76]:
# Sum along rows
torch.sum(s, dim=1)

tensor([ 9., 18.])

In [77]:
np.sum(b, axis=1)

array([ 9., 18.])

### b. Mean

In [79]:
# Mean of all values
torch.mean(s)

tensor(4.5000)

In [80]:
np.mean(b)

np.float64(4.5)

In [81]:
# Mean along columns
torch.mean(s, dim=0)

tensor([3.5000, 4.5000, 5.5000])

In [82]:
np.mean(b, axis=0)

array([3.5, 4.5, 5.5])

In [83]:
# Mean along rows
torch.mean(s, axis=1)

tensor([3., 6.])

In [84]:
np.mean(b, axis=1)

array([3., 6.])

### c. Min & Max

In [85]:
# Min/Max of all values
torch.min(s), torch.max(s)

(tensor(2.), tensor(7.))

In [86]:
np.min(b), np.max(b)

(np.float64(2.0), np.float64(7.0))

In [88]:
# Min/Max along columns
torch.min(s, dim=0)

torch.return_types.min(
values=tensor([2., 3., 4.]),
indices=tensor([0, 0, 0]))

In [89]:
torch.max(s, dim=0)

torch.return_types.max(
values=tensor([5., 6., 7.]),
indices=tensor([1, 1, 1]))

In [90]:
np.min(b, axis=0)

array([2., 3., 4.])

In [91]:
np.max(b, axis=0)

array([5., 6., 7.])

In [92]:
# Min/Max along rows
torch.min(s, dim=1), torch.max(s, dim=1)

(torch.return_types.min(
 values=tensor([2., 5.]),
 indices=tensor([0, 0])),
 torch.return_types.max(
 values=tensor([4., 7.]),
 indices=tensor([2, 2])))

In [94]:
np.min(b, axis=1), np.max(b, axis=1)

(array([2., 5.]), array([4., 7.]))

### d. argmax & argmin

In [102]:
torch.argmin(s)

tensor(0)

In [103]:
torch.argmax(s)

tensor(5)

In [104]:
np.argmin(b)

np.int64(0)

In [105]:
np.argmax(b)

np.int64(5)

### e. Product

In [95]:
torch.prod(s)

tensor(5040.)

In [96]:
np.prod(b)

np.float64(5040.0)

### f. Standard deviation

In [97]:
torch.std(s)

tensor(1.8708)

In [98]:
np.std(b)

np.float64(1.707825127659933)

### g. Variance

In [100]:
torch.var(s)

tensor(3.5000)

In [101]:
np.var(b)

np.float64(2.9166666666666665)

## 7. Matrix Operations

In [4]:
s = torch.randint(size=(2, 3), low=0, high=10)
t = torch.randint(size=(3, 2), low=0, high=10)

In [5]:
s

tensor([[6, 7, 8],
        [2, 5, 7]])

In [6]:
t

tensor([[4, 1],
        [7, 6],
        [9, 5]])

In [9]:
a = np.random.randint(size=(2, 3), low=0, high=10)
b = np.random.randint(size=(3, 2), low=0, high=10)

In [10]:
a

array([[0, 5, 8],
       [5, 0, 1]])

In [11]:
b

array([[2, 3],
       [1, 8],
       [6, 3]])

### a. Matrix Multiplication

In [12]:
torch.matmul(s, t)

tensor([[145,  88],
        [106,  67]])

In [13]:
np.matmul(a, b)

array([[53, 64],
       [16, 18]])

### b. Dot Product

In [14]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

torch.dot(vector1, vector2)

tensor(11)

In [15]:
vector3 = np.array([1, 2])
vector4 = np.array([3, 4])

np.dot(vector3, vector4)

np.int64(11)

### c. Transpose

In [20]:
torch.transpose(s, 0, 1)

tensor([[6, 2],
        [7, 5],
        [8, 7]])

In [28]:
np.transpose(a)

array([[0, 5],
       [5, 0],
       [8, 1]])

### d. Determinant

In [30]:
u = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
u

tensor([[8., 4., 0.],
        [5., 8., 4.],
        [2., 7., 3.]])

In [31]:
torch.det(u)

tensor(-60.0000)

In [39]:
c = np.random.uniform(size=(3, 3), low=0, high=10)
c

array([[1.05216401, 3.0048111 , 6.76463475],
       [6.19305238, 0.55903822, 4.61666785],
       [0.46774927, 8.80927761, 4.96467545]])

In [41]:
np.linalg.det(c)

np.float64(241.51521631789194)

### e. Inverse

In [42]:
torch.inverse(u)

tensor([[ 0.0667,  0.2000, -0.2667],
        [ 0.1167, -0.4000,  0.5333],
        [-0.3167,  0.8000, -0.7333]])

In [45]:
np.linalg.inv(c)

array([[-0.15690136,  0.18497234,  0.04178008],
       [-0.11836543,  0.00852741,  0.15334953],
       [ 0.22480914, -0.03255822, -0.07461539]])

## 8. Comparison Operations

In [47]:
it = torch.randint(size=(2, 3), low=0, high=10)
jt = torch.randint(size=(2, 3), low=0, high=10)

print(it)
print(jt)

tensor([[2, 3, 4],
        [2, 7, 5]])
tensor([[4, 4, 6],
        [0, 4, 0]])


In [49]:
inp = np.random.randint(size=(2, 3), low=0, high=10)
jnp = np.random.randint(size=(2, 3), low=0, high=10)

print(inp)
print(jnp)

[[4 0 4]
 [8 0 7]]
[[0 9 8]
 [8 9 0]]


In [50]:
it > jt

tensor([[False, False, False],
        [ True,  True,  True]])

In [51]:
inp > jnp

array([[ True, False, False],
       [False, False,  True]])

All comparison operators are supported in similar to the example above.

## 9. Special Functions

### a. log

In [54]:
torch.log(s)

tensor([[1.7918, 1.9459, 2.0794],
        [0.6931, 1.6094, 1.9459]])

In [58]:
np.log(b)

array([[0.69314718, 1.09861229],
       [0.        , 2.07944154],
       [1.79175947, 1.09861229]])

### b. exp

In [59]:
torch.exp(s)

tensor([[ 403.4288, 1096.6332, 2980.9580],
        [   7.3891,  148.4132, 1096.6332]])

In [60]:
np.exp(a)

array([[1.00000000e+00, 1.48413159e+02, 2.98095799e+03],
       [1.48413159e+02, 1.00000000e+00, 2.71828183e+00]])

### c. sqrt

In [61]:
torch.sqrt(s)

tensor([[2.4495, 2.6458, 2.8284],
        [1.4142, 2.2361, 2.6458]])

In [62]:
np.sqrt(a)

array([[0.        , 2.23606798, 2.82842712],
       [2.23606798, 0.        , 1.        ]])

### d. Sigmoid

In [63]:
torch.sigmoid(s)

tensor([[0.9975, 0.9991, 0.9997],
        [0.8808, 0.9933, 0.9991]])

In [65]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-2, 0, 2])
print(sigmoid(x))

[0.11920292 0.5        0.88079708]


### e. Softmax

In [67]:
torch.softmax(u, dim=0)

tensor([[0.9503, 0.0132, 0.0132],
        [0.0473, 0.7214, 0.7214],
        [0.0024, 0.2654, 0.2654]])

In [68]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x = np.array([1, 2, 3])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]


In [71]:
torch.softmax(torch.tensor([1.0, 2.0, 3.0]), dim=-1)

tensor([0.0900, 0.2447, 0.6652])

### f. ReLu

In [72]:
torch.relu(u)

tensor([[8., 4., 0.],
        [5., 8., 4.],
        [2., 7., 3.]])

In [74]:
def relu(x):
    return np.maximum(0, x)

x = np.array([-2, -1, 0, 3])
print(relu(x))

[0 0 0 3]


## 10. Inplace Operations

In [77]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.5705, 0.7714, 0.4484],
        [0.0304, 0.6443, 0.3271]])
tensor([[0.4704, 0.8846, 0.4181],
        [0.5746, 0.0765, 0.4328]])


In [78]:
m.add_(n)

tensor([[1.0409, 1.6560, 0.8664],
        [0.6050, 0.7208, 0.7599]])

In [79]:
m

tensor([[1.0409, 1.6560, 0.8664],
        [0.6050, 0.7208, 0.7599]])

In [80]:
o = np.random.randint(size=(2, 3), low=0, high=10)
p = np.random.randint(size=(2, 3), low=0, high=10)

In [83]:
np.add(o, p, out=o) # or o += p

array([[18,  8, 14],
       [13, 12,  9]])

In [84]:
o

array([[18,  8, 14],
       [13, 12,  9]])

In [89]:
u = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
u

tensor([[3., 3., 6.],
        [2., 2., 8.],
        [6., 5., 1.]])

In [90]:
u.sigmoid_()

tensor([[0.9526, 0.9526, 0.9975],
        [0.8808, 0.8808, 0.9997],
        [0.9975, 0.9933, 0.7311]])

In [91]:
u

tensor([[0.9526, 0.9526, 0.9975],
        [0.8808, 0.8808, 0.9997],
        [0.9975, 0.9933, 0.7311]])

Note: Suffixing an underscore to the method makes it an inplace operation.

## 11. Copying a Tensor

In [92]:
a = torch.rand(2,3)
a

tensor([[0.1028, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

### Referenced copy

In [93]:
b = a

In [94]:
b

tensor([[0.1028, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

In [95]:
a[0][0] = 0
a

tensor([[0.0000, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

In [96]:
b

tensor([[0.0000, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

In [97]:
id(a), id(b)

(135981405677248, 135981405677248)

### Cloned copy

In [98]:
b = a.clone()

In [99]:
a[0][0] = 1
a

tensor([[1.0000, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

In [100]:
b

tensor([[0.0000, 0.3518, 0.7320],
        [0.8140, 0.0568, 0.2666]])

In [101]:
id(a), id(b)

(135981405677248, 135981406140400)

## 12. Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.6146, 0.7502, 0.8164],
        [0.2579, 0.6280, 0.4347]], device='cuda:0')

In [7]:
# moving an existing tensor to GPU
t = torch.rand(2, 3)
t

tensor([[0.9788, 0.9670, 0.6672],
        [0.1342, 0.0434, 0.4591]])

In [9]:
gt = t.to(device)
gt

tensor([[0.9788, 0.9670, 0.6672],
        [0.1342, 0.0434, 0.4591]], device='cuda:0')

In [10]:
gt + 5

tensor([[5.9788, 5.9670, 5.6672],
        [5.1342, 5.0434, 5.4591]], device='cuda:0')

In [11]:
import time

size = 10000 # Large matrix size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 7.481740 seconds
Time on GPU: 0.728763 seconds

Speedup (CPU time / GPU time): 10.266350962081098


## 13. Reshaping Tensors

In [12]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
b = np.ones([4, 4])
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### a. reshape

In [14]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [15]:
b.reshape(2, 2, 2, 2)

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

### b. flatten

In [16]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### c. permute

In [20]:
a = torch.ones(2, 3, 4)
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [23]:
b = np.ones([2, 3, 4])
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
a.permute(2, 0, 1)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [26]:
b.transpose(2, 0, 1)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### d. unsqueeze

In [27]:
a = torch.rand(226, 226, 3)

In [28]:
a.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [31]:
b = np.random.rand(226, 226, 3)

In [34]:
np.expand_dims(b, axis=0).shape

(1, 226, 226, 3)

### e. squeeze

In [35]:
a = torch.rand(1, 20)
a.shape

torch.Size([1, 20])

In [36]:
a.squeeze(0).shape

torch.Size([20])

In [38]:
b = np.expand_dims(b, axis=0)
b.shape

(1, 226, 226, 3)

In [40]:
b.squeeze().shape

(226, 226, 3)

## 14. NumPy and PyTorch

In [41]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [44]:
b = a.numpy()
b

array([1, 2, 3])

In [45]:
torch.from_numpy(b)

tensor([1, 2, 3])