# Pytorch Training Pipeline Improvement Using NN Module and torch.optim

In [1]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## 1. Data loading

- Breast Cancer Detection Dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

## 2. Data Preprocessing

- Train-test split
- Scaling
- Label encoding
- Tensor conversion

### a. Train-test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### b. Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.39560634, -1.27464065, -1.34017757, ..., -0.94314547,
         0.68552844,  0.06829253],
       [-0.72875137, -1.99720507, -0.74512445, ..., -0.99935725,
         0.86951719, -0.51903131],
       [-0.65550156, -0.49224606, -0.68246572, ..., -0.9024977 ,
        -0.17138211, -0.13693711],
       ...,
       [-0.78791467, -1.20560583, -0.82457407, ..., -1.54394668,
        -0.2071577 , -1.10190573],
       [-0.21036812,  2.60511606, -0.22870187, ..., -0.53878329,
        -1.16458062, -0.38499244],
       [-0.09767611, -0.83051666, -0.14556644, ..., -1.2113603 ,
        -1.73869365, -0.86608631]], shape=(455, 30))

### c. Label encoding

In [9]:
y_train

63     B
313    B
399    B
258    M
94     M
      ..
423    B
486    B
276    B
455    B
442    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,

### d. Numpy array to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

## 3. Defining The Model

In [15]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        out = self.linear(X)
        return self.sigmoid(out)

## 4. Training Pipeline

In [18]:
from torchinfo import summary

In [19]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
summary(model, input_size=(455, 30))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06

In [20]:
# Important Parameters

learning_rate = 0.1
epochs = 25

In [21]:
# define loss function
loss_function = nn.BCELoss()

In [22]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [23]:
# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

    # backward pass
    loss.backward()

    # clear gradients
    optimizer.zero_grad()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7315108180046082
Epoch: 2, Loss: 0.7315108180046082
Epoch: 3, Loss: 0.7315108180046082
Epoch: 4, Loss: 0.7315108180046082
Epoch: 5, Loss: 0.7315108180046082
Epoch: 6, Loss: 0.7315108180046082
Epoch: 7, Loss: 0.7315108180046082
Epoch: 8, Loss: 0.7315108180046082
Epoch: 9, Loss: 0.7315108180046082
Epoch: 10, Loss: 0.7315108180046082
Epoch: 11, Loss: 0.7315108180046082
Epoch: 12, Loss: 0.7315108180046082
Epoch: 13, Loss: 0.7315108180046082
Epoch: 14, Loss: 0.7315108180046082
Epoch: 15, Loss: 0.7315108180046082
Epoch: 16, Loss: 0.7315108180046082
Epoch: 17, Loss: 0.7315108180046082
Epoch: 18, Loss: 0.7315108180046082
Epoch: 19, Loss: 0.7315108180046082
Epoch: 20, Loss: 0.7315108180046082
Epoch: 21, Loss: 0.7315108180046082
Epoch: 22, Loss: 0.7315108180046082
Epoch: 23, Loss: 0.7315108180046082
Epoch: 24, Loss: 0.7315108180046082
Epoch: 25, Loss: 0.7315108180046082


In [24]:
model.linear.weight

Parameter containing:
tensor([[ 0.0070,  0.1572, -0.0707,  0.0061,  0.1660, -0.1592, -0.1379, -0.0679,
          0.0849,  0.1024,  0.0035,  0.1179,  0.1569,  0.0098, -0.0658,  0.1033,
         -0.1609,  0.0813,  0.1440, -0.1080, -0.1618,  0.0113, -0.0022,  0.0618,
         -0.0988, -0.0482,  0.0986,  0.1188, -0.0081,  0.0209]],
       requires_grad=True)

In [25]:
model.linear.bias

Parameter containing:
tensor([0.0978], requires_grad=True)

## 5. Evaluation

In [26]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6491228342056274
