# Numpy Essentials

- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing in Python.

Topics Covered:
1. Introduction to Tensors
2. Array Creation Methods
3. Data Types
4. Scalar Operations
5. Element-wise Operations
6. Special Functions
7. Comparison Operations
8. Reduction Operations
9. Matrix Operations
10. Linear Algebra Paradigm vs Looping Paradigm
11. Copying and Reshaping Arrays
12. In-place Operations

In [2]:
import numpy as np

## 1️⃣ Introduction to Tensors
- A tensor is a generalization of vectors and matrices.
| Tensor Type         | Dimension |
| ------------------- | --------- |
| Scalar              | 0D        |
| Vector              | 1D        |
| Matrix              | 2D        |
| Higher-order Tensor | 3D+       |

NumPy arrays can represent all of these.

In [3]:
scalar = np.array(5)

vector = np.array([1,2,3])

matrix = np.array([[1,2],
                   [3,4]])

tensor3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(matrix.shape)

(2, 2)


### 1D Arrays

In [2]:
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

### 2D Arrays

In [21]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 1]
list3 = [2, 3, 4, 5, 9]

arr = np.array([list1, list2, list3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 9]])

In [6]:
arr.shape

(3, 5)

### Indexing

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
arr[0]

np.int64(1)

In [18]:
arr[0:3]

array([1, 2, 3])

In [24]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 1]
list3 = [2, 3, 4, 5, 9]

arr = np.array([list1, list2, list3])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [2, 3, 4, 5, 9]])

In [23]:
arr[1:3, 1:4]

array([[7, 8, 9],
       [3, 4, 5]])

## 2️⃣ Array Creation Methods
| Function     | Description            |
| ------------ | ---------------------- |
| `array()`    | Create array from list |
| `zeros()`    | Array of zeros         |
| `ones()`     | Array of ones          |
| `arange()`   | Range of values        |
| `linspace()` | Evenly spaced numbers  |
| `random`     | Random values          |

In [4]:
a = np.array([1,2,3])

b = np.zeros((2,3))

c = np.ones((3,3))

d = np.arange(0,10,2)

e = np.linspace(0,1,5)

f = np.random.rand(3,3)

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [27]:
np.ones((4, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [25]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.random.rand(3, 3)

array([[0.52223035, 0.64132833, 0.58675151],
       [0.37598638, 0.42077116, 0.87678043],
       [0.37954727, 0.87066427, 0.27732873]])

## 3️⃣️ Data Types

NumPy arrays have fixed data types, which improves performance.
| Type    |
| ------- |
| int32   |
| int64   |
| float32 |
| float64 |
| bool    |


In [5]:
a = np.array([1,2,3], dtype=np.float32)

print(a.dtype)

float32


In [6]:
# Convert types
b = a.astype(np.int32)
print(b.dtype)

int32


## 4️⃣ Scalar Operations
Operations between array and scalar apply to every element.

In [7]:
a = np.array([1,2,3])

print(a + 10)
print(a * 2)
print(a / 2)

[11 12 13]
[2 4 6]
[0.5 1.  1.5]


## 5️⃣ Element-wise Operations
Operations between arrays occur element by element.

Arrays must have same shape or broadcastable shapes.

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a / b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 6️⃣ Special Functions
NumPy provides many mathematical functions.
| Function | Description |
| -------- | ----------- |
| `sqrt()` | Square root |
| `exp()`  | Exponential |
| `log()`  | Natural log |
| `sin()`  | Sine        |
| `cos()`  | Cosine      |

In [9]:
a = np.array([1,4,9])

print(np.sqrt(a))

print(np.exp(a))

print(np.log(a))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[0.         1.38629436 2.19722458]


### Random Number Generation

In [45]:
np.random.randint(0, 100, 3)

array([65, 64, 88], dtype=int32)

In [46]:
np.random.random_sample((1, 3))

array([[0.79264446, 0.41751452, 0.49361808]])

## 7️⃣Comparison Operations
Comparison operations return boolean arrays.

In [34]:
a = np.array([1,5,3])

print(a > 2)

print(a == 3)

[False  True  True]
[False False  True]


### Boolean indexing / Conditional filtering

In [35]:
a[a > 2]

array([5, 3])

In [36]:
a[a <= 3]

array([1, 3])

## 8️⃣ Reduction Operations
Reduction operations reduce an array to a single value.
| Function |
| -------- |
| `sum()`  |
| `mean()` |
| `max()`  |
| `min()`  |
| `std()`  |

In [12]:
a = np.array([1,2,3,4])

print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.std(a))

10
2.5
4
1.118033988749895


In [14]:
# Axis based reduction
matrix = np.array([[1,2],
                   [3,4]])

print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))

[4 6]
[3 7]


## 9️⃣ Matrix Operations
NumPy supports matrix algebra operations.

Matrix multiplication uses `@` or `np.dot`.

### Matrix multiplication

In [37]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

C = A @ B

print(C)

[[19 22]
 [43 50]]


## 🔟 Linear Algebra Paradigm vs Looping Paradigm
Instead of looping manually, use vectorized operations.

### Looping (slow)

In [39]:
result = []

for i in range(len(a)):
    result.append(a[i] * 2)

result

[np.int64(2), np.int64(10), np.int64(6)]

### Vectorized
Advantages:
- Faster
- Cleaner code
- Uses optimized C backend

In [40]:
a * 2

array([ 2, 10,  6])

## 1️⃣1️⃣ Copying and Reshaping Arrays

### Reshape

In [41]:
a = np.arange(6)

b = a.reshape(2,3)

print(b)

[[0 1 2]
 [3 4 5]]


In [42]:
b.flatten()

array([0, 1, 2, 3, 4, 5])

### Copy

In [43]:
a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print(a)

[1 2 3]


## 1️⃣2️⃣ In-place Operations
In-place operations modify the original array instead of creating a new one.

In [44]:
a = np.array([1,2,3])

a += 5

print(a)

[6 7 8]
