# Pandas Essentials

## 1️⃣ Pandas Data Frame and Data Series

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.arange(0, 15).reshape(3, 5), index=['Row1', 'Row2', 'Row3'], columns=['Col1', 'Col2', 'Col3', 'Col4', 'Col5'])
df.head()

,Col1,Col2,Col3,Col4,Col5
Row1,0,1,2,3,4
Row2,5,6,7,8,9
Row3,10,11,12,13,14


In [3]:
# df.to_csv('test.csv')

In [17]:
df.shape

(3, 5)

In [18]:
type(df)

pandas.DataFrame

In [21]:
type(df.iloc[0])

pandas.Series

## 2️⃣ Accessing elements

### Head, Tail, Sample

In [23]:
df.head()

,Col1,Col2,Col3,Col4,Col5
Row1,0,1,2,3,4
Row2,5,6,7,8,9
Row3,10,11,12,13,14


In [24]:
df.tail()

,Col1,Col2,Col3,Col4,Col5
Row1,0,1,2,3,4
Row2,5,6,7,8,9
Row3,10,11,12,13,14


In [26]:
df.sample(2)

,Col1,Col2,Col3,Col4,Col5
Row1,0,1,2,3,4
Row2,5,6,7,8,9


### Columns

In [27]:
df.columns

Index(['Col1', 'Col2', 'Col3', 'Col4', 'Col5'], dtype='str')

In [29]:
df.Col1

Row1     0
Row2     5
Row3    10
Name: Col1, dtype: int64

In [4]:
df['Col1']

Row1     0
Row2     5
Row3    10
Name: Col1, dtype: int64

In [5]:
df[['Col1', 'Col2']]

,Col1,Col2
Row1,0,1
Row2,5,6
Row3,10,11


### Rows

In [6]:
# 1. loc 2. iloc

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Col5    4
Name: Row1, dtype: int64

In [7]:
df.loc[['Row1', 'Row2']]

,Col1,Col2,Col3,Col4,Col5
Row1,0,1,2,3,4
Row2,5,6,7,8,9


In [30]:
# Integer indexing rows
df.iloc[0]

Col1    0
Col2    1
Col3    2
Col4    3
Col5    4
Name: Row1, dtype: int64

In [8]:
type(df.loc['Row1'])

pandas.Series

### Slicing

In [9]:
df.iloc[0:2, 0:2]

,Col1,Col2
Row1,0,1
Row2,5,6


In [10]:
type(df.iloc[0:2, 0:2])

pandas.DataFrame

In [11]:
type(df.iloc[0:2, 0])

pandas.Series

## 3️⃣ Convert Data Frames into numpy arrays

In [12]:
df.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
df.loc['Row1'].values

array([0, 1, 2, 3, 4])

## 4️⃣ Dataframe Operations

### Aggregation

In [38]:
df.loc['Row1'].max()

np.int64(4)

In [40]:
df.loc['Row1'].sum()

np.int64(10)

In [43]:
df.loc['Row1'].mean()

np.float64(2.0)

### Conditional Filtering

In [47]:
df[df['Col1'] >= 5]

,Col1,Col2,Col3,Col4,Col5
Row2,5,6,7,8,9
Row3,10,11,12,13,14


### Describe data

In [48]:
df.describe()

,Col1,Col2,Col3,Col4,Col5
count,3.0,3.0,3.0,3.0,3.0
mean,5.0,6.0,7.0,8.0,9.0
std,5.0,5.0,5.0,5.0,5.0
min,0.0,1.0,2.0,3.0,4.0
25%,2.5,3.5,4.5,5.5,6.5
50%,5.0,6.0,7.0,8.0,9.0
75%,7.5,8.5,9.5,10.5,11.5
max,10.0,11.0,12.0,13.0,14.0


### Null Check

In [14]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
Col5    0
dtype: int64

### Category check

In [15]:
df['Col1'].value_counts()

Col1
0     1
5     1
10    1
Name: count, dtype: int64

In [16]:
df['Col2'].unique()

array([ 1,  6, 11])

## 5️⃣ Dataframe creation methods

Dataframes can be read from various data sources such as:
- CSV files
- Excel files
- Database

However, data in the form of native python objects can also be converted into dataframes. The methods are discussed below.

### CSV and Excel files

In [49]:
# df = pd.read_csv("weather_data.csv")
# df = pd.read_excel("weather_data.xlsx", sheet_name="Sheet1")

### Dictionary of lists

In [50]:
weather_data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'windspeed': [6, 7, 2],
    'event': ['Rain', 'Sunny', 'Snow']
}

df = pd.DataFrame(data=weather_data)
df

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow


### List of dictionaries

In [52]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
]

df = pd.DataFrame(weather_data)
df

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow


### List of tuples

In [51]:
weather_data = [
    ('1/1/2017', 32, 6, 'Rain'),
    ('1/2/2017', 35, 7, 'Sunny'),
    ('1/3/2017', 28, 2, 'Snow')
]
df = pd.DataFrame(data=weather_data, columns=["day", "temperature", "windspeed", "event"])
df

,day,temperature,windspeed,event
0,1/1/2017,32,6,Rain
1,1/2/2017,35,7,Sunny
2,1/3/2017,28,2,Snow


## 6️⃣ Reading CSV & Excel files

### CSV Files

#### Skip rows

In [ ]:
# df = pd.read_csv("stock_data.csv", skiprows=1)

#### Append header names

In [53]:
# df = pd.read_csv("stock_data.csv", header=None, names=["ticker", "eps", "revenue", "price", "people"])

#### Read n rows

In [54]:
# df = pd.read_csv("stock_data.csv", nrows=3)

#### Handling na values

In [ ]:
# df = pd.read_csv("stock_data.csv", na_values=["not available", "n.a."])

# df = pd.read_csv("stock_data.csv", na_values={
#         'eps': ["not available", "n.a."],
#         'revenue': ["not available", "n.a.", -1],
#         'people': ["not available", "n.a."],
#     })

#### Save df as csv file

In [55]:
# df.to_csv('new.csv', index=False)

In [56]:
# df.to_csv("new.csv", columns=['tickers', 'eps'])
# df.to_csv("new.csv", header=False)

### Excel files

#### Read Excel with converters

In [57]:
# def convert_people_cell(cell):
#     if cell=="n.a.":
#         return 'sam walton'
#     return cell

# def convert_eps_cell(cell):
#     if cell=="not available":
#         return None
#     return cell

# df = pd.read_excel("stock_data.xlsx", "Sheet1", converters = {
#         'people': convert_people_cell,
#         'eps': convert_eps_cell
#     })

#### Save df as xlsx file

In [58]:
# df.to_excel("new.xlsx", sheet_name="stocks", index=False)

In [62]:
# Specify row and col start

# df.to_excel("new.xlsx", sheet_name="stocks", startrow=1, startcol=2)

In [61]:
# Using Excel Writer

# df_stocks = pd.DataFrame({
#     'tickers': ['GOOGL', 'WMT', 'MSFT'],
#     'price': [845, 65, 64 ],
#     'pe': [30.37, 14.26, 30.97],
#     'eps': [27.82, 4.61, 2.12]
# })

# df_weather =  pd.DataFrame({
#     'day': ['1/1/2017','1/2/2017','1/3/2017'],
#     'temperature': [32,35,28],
#     'event': ['Rain', 'Sunny', 'Snow']
# })

# with pd.ExcelWriter('stocks_weather.xlsx') as writer:
#     df_stocks.to_excel(writer, sheet_name="stocks")
#     df_weather.to_excel(writer, sheet_name="weather")

## 7️⃣ Handling NA values

In [84]:
df = pd.read_csv("weather_data_missing.csv", parse_dates=["day"])
df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,NaN,9.0,Sunny
2,2017-01-05,28.0,NaN,Snow
3,2017-01-06,NaN,7.0,NaN
4,2017-01-07,32.0,NaN,Rain
5,2017-01-08,NaN,NaN,Sunny
6,2017-01-09,NaN,NaN,NaN
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


### Fill all NA

In [64]:
new_df = df.fillna(0)
new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,0.0,9.0,Sunny
2,2017-01-05,28.0,0.0,Snow
3,2017-01-06,0.0,7.0,0
4,2017-01-07,32.0,0.0,Rain
5,2017-01-08,0.0,0.0,Sunny
6,2017-01-09,0.0,0.0,0
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


### Fill NA based on Cols

In [66]:
new_df = df.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'no event'
    })

new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,0.0,9.0,Sunny
2,2017-01-05,28.0,0.0,Snow
3,2017-01-06,0.0,7.0,no event
4,2017-01-07,32.0,0.0,Rain
5,2017-01-08,0.0,0.0,Sunny
6,2017-01-09,0.0,0.0,no event
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


### bfill and ffill

In [67]:
# new_df = df.ffill()
new_df = df.bfill(limit=1)
new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,28.0,9.0,Sunny
2,2017-01-05,28.0,7.0,Snow
3,2017-01-06,32.0,7.0,Rain
4,2017-01-07,32.0,NaN,Rain
5,2017-01-08,NaN,NaN,Sunny
6,2017-01-09,34.0,8.0,Cloudy
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


### Drop NA

In [69]:
# new_df = df.dropna()
# new_df = df.dropna(how="all")
new_df = df.dropna(thresh=2)

new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,NaN,9.0,Sunny
2,2017-01-05,28.0,NaN,Snow
3,2017-01-06,NaN,7.0,NaN
4,2017-01-07,32.0,NaN,Rain
5,2017-01-08,NaN,NaN,Sunny
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


## 8️⃣ Dataframe special methods

### Replace Method

In [75]:
new_df = df.replace({
        'temperature': 40.0,
        'windspeed': [12.0, 9.0],
        'event': '0'
    }, np.nan)

new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rain
1,2017-01-04,NaN,NaN,Sunny
2,2017-01-05,28.0,NaN,Snow
3,2017-01-06,NaN,7.0,NaN
4,2017-01-07,32.0,NaN,Rain
5,2017-01-08,NaN,NaN,Sunny
6,2017-01-09,NaN,NaN,NaN
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,NaN,NaN,Sunny


In [85]:
new_df = df.replace({
        'Rain': 'Rainy'
    })

new_df

,day,temperature,windspeed,event
0,2017-01-01,32.0,6.0,Rainy
1,2017-01-04,NaN,9.0,Sunny
2,2017-01-05,28.0,NaN,Snow
3,2017-01-06,NaN,7.0,NaN
4,2017-01-07,32.0,NaN,Rainy
5,2017-01-08,NaN,NaN,Sunny
6,2017-01-09,NaN,NaN,NaN
7,2017-01-10,34.0,8.0,Cloudy
8,2017-01-11,40.0,12.0,Sunny


In [86]:
df = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})

df

,score,student
0,exceptional,rob
1,average,maya
2,good,parthiv
3,poor,tom
4,average,julian
5,exceptional,erica


In [87]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1, 2, 3, 4])

,score,student
0,4,rob
1,2,maya
2,3,parthiv
3,1,tom
4,2,julian
5,4,erica


### Groupby Method

In [88]:
g = df.groupby('score')
g

In [89]:
for group, group_df in g:
    print(group)
    print(group_df)

average
     score student
1  average    maya
4  average  julian
exceptional
         score student
0  exceptional     rob
5  exceptional   erica
good
  score  student
2  good  parthiv
poor
  score student
3  poor     tom


In [90]:
g.get_group('average')

,score,student
1,average,maya
4,average,julian


In the case of numeric columns in the data:
- Aggregate functions such as `max()`, `sum()`, etc. can be run on each group
- Groups can be described using `describe()`

### Concat Method

In [92]:
bangladesh_weather = {
    "city": ["dhaka", "chittagong", "sylhet"],
    "temperature": [32, 45, 30],
    "humidity": [80, 60, 78]
}

bdf = pd.DataFrame(bangladesh_weather)

bdf

,city,temperature,humidity
0,dhaka,32,80
1,chittagong,45,60
2,sylhet,30,78


In [93]:
us_weather = {
    "city": ["new york", "chicago", "orlando"],
    "temperature": [23, 14, 35],
    "humidity": [68, 65, 75]
}

usdf = pd.DataFrame(us_weather)

usdf

,city,temperature,humidity
0,new york,23,68
1,chicago,14,65
2,orlando,35,75


In [94]:
# Stacking dataframes

df = pd.concat([bdf, usdf])
df

,city,temperature,humidity
0,dhaka,32,80
1,chittagong,45,60
2,sylhet,30,78
0,new york,23,68
1,chicago,14,65
2,orlando,35,75


In [96]:
# Resetting index

df = pd.concat([bdf, usdf], ignore_index=True)
df

,city,temperature,humidity
0,dhaka,32,80
1,chittagong,45,60
2,sylhet,30,78
3,new york,23,68
4,chicago,14,65
5,orlando,35,75


In [97]:
# Preserving separation using keys

df = pd.concat([bdf, usdf], keys=["bd", "us"])
df

city  temperature  humidity
bd 0       dhaka           32        80
   1  chittagong           45        60
   2      sylhet           30        78
us 0    new york           23        68
   1     chicago           14        65
   2     orlando           35        75

In [98]:
df.loc["bd"]

,city,temperature,humidity
0,dhaka,32,80
1,chittagong,45,60
2,sylhet,30,78


In [100]:
# Appending a new column

s = pd.Series(["Humid", "Dry", "Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: str

In [101]:
df = pd.concat([bdf, s], axis=1)
df

,city,temperature,humidity,event
0,dhaka,32,80,Humid
1,chittagong,45,60,Dry
2,sylhet,30,78,Rain


### Merge Method

In [102]:
df1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando", "baltimore"],
    "temperature": [21, 14, 35, 32],
})

df1

,city,temperature
0,new york,21
1,chicago,14
2,orlando,35
3,baltimore,32


In [103]:
df2 = pd.DataFrame({
    "city": ["chicago", "new york", "san francisco"],
    "humidity": [65, 68, 75],
})

df2

,city,humidity
0,chicago,65
1,new york,68
2,san francisco,75


In [104]:
# Analogous to SQL joins

# df3 = pd.merge(df1, df2, on="city")
df3 = pd.merge(df1, df2, on="city", how="outer", indicator=True)
# df3 = pd.merge(df1, df2, on="city", how="left")
# df3 = pd.merge(df1, df2, on="city", how="right")

df3

,city,temperature,humidity,_merge
0,baltimore,32.0,NaN,left_only
1,chicago,14.0,65.0,both
2,new york,21.0,68.0,both
3,orlando,35.0,NaN,left_only
4,san francisco,NaN,75.0,right_only
